name: river_workspace
publish_to: none

environment:
  sdk: ^3.11.2

workspace:
  - packages/bintools
  - packages/river
  - packages/river_adl
  - packages/river_emulator
  - packages/river_hdl
  - packages/river_maskrom

dependency_overrides:
  harbor:
    git:
      url: https://github.com/murdoa/harbor.git
      path: packages/harbor
      ref: 57b7bdccb1b2e2bef2c87c387f339d00b2274d2a

dev_dependencies:
  coverage: ^1.15.0
